//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X2AddOnTechTreeEditor {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("X2AddOnTechTreeEditor.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ClassNames {
            get {
                return ResourceManager.GetString("ClassNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktuelle Auswahl: {0} ähnelt.
        /// </summary>
        internal static string MainForm_CurrentSelection {
            get {
                return ResourceManager.GetString("MainForm_CurrentSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es gibt noch ungespeicherte Änderungen. Sollen diese gespeichert werden? ähnelt.
        /// </summary>
        internal static string MainForm_Message_CloseProjectSaveChanges {
            get {
                return ResourceManager.GetString("MainForm_Message_CloseProjectSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt schließen ähnelt.
        /// </summary>
        internal static string MainForm_Message_CloseProjectSaveChanges_Title {
            get {
                return ResourceManager.GetString("MainForm_Message_CloseProjectSaveChanges_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade Farbpalette... ähnelt.
        /// </summary>
        internal static string MainForm_Status_LoadingPal {
            get {
                return ResourceManager.GetString("MainForm_Status_LoadingPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade Projektdatei... ähnelt.
        /// </summary>
        internal static string MainForm_Status_LoadingProjectFile {
            get {
                return ResourceManager.GetString("MainForm_Status_LoadingProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übergebe Renderdaten... ähnelt.
        /// </summary>
        internal static string MainForm_Status_PassRenderData {
            get {
                return ResourceManager.GetString("MainForm_Status_PassRenderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bereite Baum-Rendering vor... ähnelt.
        /// </summary>
        internal static string MainForm_Status_PreparingTreeRendering {
            get {
                return ResourceManager.GetString("MainForm_Status_PreparingTreeRendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bereit ähnelt.
        /// </summary>
        internal static string MainForm_Status_Ready {
            get {
                return ResourceManager.GetString("MainForm_Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt speichern... ähnelt.
        /// </summary>
        internal static string MainForm_Status_Saving {
            get {
                return ResourceManager.GetString("MainForm_Status_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt gespeichert. ähnelt.
        /// </summary>
        internal static string MainForm_Status_SavingSuccessful {
            get {
                return ResourceManager.GetString("MainForm_Status_SavingSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X2-AddOn :: Technologiebaum bearbeiten {0} ähnelt.
        /// </summary>
        internal static string MainForm_Title {
            get {
                return ResourceManager.GetString("MainForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nahrung
        ///Holz
        ///Stein
        ///Gold
        ///Bevölkerungslimit
        ///Bekehrungsreichweite
        ///Current Age
        ///Relics Captured
        ///Trade Bonus
        ///Trade Goods
        ///Trade Production
        ///Population (Both Current and Headroom)
        ///Corpse Decay Time
        ///Discovery
        ///Monuments/Ruins Captured
        ///Meat Storage
        ///Berry Storage
        ///Fish Storage
        ///Unknown
        ///Total Units Owned
        ///Units Killed
        ///Research Count
        ///% Map Explored
        ///Castle Age tech index
        ///Imperial Age tech index
        ///Feudal Age tech index
        ///Attack Warning Sound
        ///Enable Monk Conversion
        ///Enable Building Conversion
        ///Unused
        ///Bui [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ResourceTypes {
            get {
                return ResourceManager.GetString("ResourceTypes", resourceCulture);
            }
        }
    }
}
